### ISSUE TITLE
No way to pick Mutilple Files?

### ISSUE THREAD

**Issue by tong233** [kaancelen/react-native-nononsense-file-picker#1]
Hi,thanks for your library.Can I pick Mutilple Files like NoNonsense-FilePicker.

**Comment by kaancelen** [comment]
Hi,
I didn't add such feature but you can fork and implement for yourself.
You can check RNNoNonsenseFilePickerModule#onShowActivityResult method, in here I get the first item.
If you change the implementation, you can have it.

Sorry about the trouble
Regards,

**Comment by tong233** [comment]
Thank you for your answer.
